
[modules]

	#Module for More Industrial Foreging Addons
	[modules.addons]
		enabled = true

		[modules.addons.efficiency_addon_3]
			enabled = true

		[modules.addons.efficiency_addon_4]
			enabled = true

		[modules.addons.speed_addon_4]
			enabled = true

		[modules.addons.speed_addon_3]
			enabled = true

		[modules.addons.netherite_gear]
			enabled = true

		[modules.addons.processing_addon_4]
			enabled = true

		[modules.addons.processing_addon_3]
			enabled = true

